version: '3.8'

services:
  backend:
    build:
      context: /Users/sophia.paiao/sophia-app-financeiro/app/backend
    ports:
      - "5001:3000"
    volumes:
      - /Users/sophia.paiao/sophia-app-financeiro/app/backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: /Users/sophia.paiao/sophia-app-financeiro/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /Users/sophia.paiao/sophia-app-financeiro/app:/app
    environment:
      NODE_ENV: development
